theme: jekyll-theme-minimal
title: Minimal theme
logo: https://w7.pngwing.com/pngs/986/608/png-transparent-computer-icons-github-github-white-face-monochrome.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
